"""add_publish_time_to_feature_set

Revision ID: 007fccb3d541
Revises: 5f1351c88a19
Create Date: 2022-06-22 10:36:41.875501

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "007fccb3d541"
down_revision = "5f1351c88a19"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_sets", sa.Column("publish_time", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature_sets", "publish_time")
    # ### end Alembic commands ###
