"""Add background task table

Revision ID: 077af998c588
Revises: 32bae1b0e29c
Create Date: 2022-06-02 10:31:06.166458

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '077af998c588'
down_revision = '32bae1b0e29c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_task',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('project', sa.String(length=255), nullable=True),
    sa.Column('created', sa.TIMESTAMP(), nullable=True),
    sa.Column('updated', sa.TIMESTAMP(), nullable=True),
    sa.Column('state', sa.String(length=255), nullable=True),
    sa.Column('timeout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'project', name='_background_task_uc')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('background_task')
    # ### end Alembic commands ###
