"""market_place_to_hub

Revision ID: 28383af526f3
Revises: c905d15bd91d
Create Date: 2023-04-24 11:06:36.177314

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "28383af526f3"
down_revision = "c905d15bd91d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("marketplace_sources", "hub_sources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("hub_sources", "marketplace_sources")
    # ### end Alembic commands ###
