"""Adding background task table

Revision ID: 7b22e42063dd
Revises: 32bae1b0e29c
Create Date: 2022-05-30 08:06:37.758009

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7b22e42063dd"
down_revision = "32bae1b0e29c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("uid", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("project", sa.String(length=255), nullable=True),
        sa.Column("creation_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("update_time", sa.TIMESTAMP(), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("background_task")
    # ### end Alembic commands ###
