"""add requested_logs column and index to runs

Revision ID: 88e656800d6a
Revises: ee041e8fdaa0
Create Date: 2023-01-11 11:21:46.882374

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "88e656800d6a"
down_revision = "ee041e8fdaa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.add_column(sa.Column("requested_logs", sa.BOOLEAN(), nullable=True))
        batch_op.create_index(
            op.f("ix_runs_requested_logs"), ["requested_logs"], unique=False
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.drop_index(op.f("ix_runs_requested_logs"))
        batch_op.drop_column("requested_logs")
    # ### end Alembic commands ###
