"""Adding data versions table

Revision ID: 9d16de5f03a7
Revises: c4af40b0bf61
Create Date: 2021-10-04 16:08:05.267113

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9d16de5f03a7"
down_revision = "c4af40b0bf61"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "data_versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("version", sa.String(255, collation="utf8_bin"), nullable=True),
        sa.Column("created", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("version", name="_versions_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("data_versions")
    # ### end Alembic commands ###
