"""Adding name and updated to runs table

Revision ID: b86f5b53f3d7
Revises: 4903aef6a91d
Create Date: 2022-01-08 19:28:45.141873

"""
from alembic import op
import sqlalchemy as sa
import mlrun.api.utils.db.sql_collation


# revision identifiers, used by Alembic.
revision = 'b86f5b53f3d7'
down_revision = '4903aef6a91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('runs', sa.Column('name', sa.String(length=255, collation=mlrun.api.utils.db.sql_collation.SQLCollationUtil.collation()), nullable=False))
    op.add_column('runs', sa.Column('updated', sa.TIMESTAMP(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('runs', 'updated')
    op.drop_column('runs', 'name')
    # ### end Alembic commands ###
