"""create new artifact table

Revision ID: bfa4cac00e7f
Revises: ee041e8fdaa0
Create Date: 2023-01-10 12:35:34.335552

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "bfa4cac00e7f"
down_revision = "ee041e8fdaa0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("artifacts", "legacy_artifacts")
    op.rename_table("artifacts_labels", "legacy_artifacts_labels")
    op.rename_table("artifacts_tags", "legacy_artifacts_tags")

    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("key", sa.String(length=255, collation="utf8_bin"), nullable=True),
        sa.Column("iter", sa.Integer(), nullable=True),
        sa.Column(
            "project", sa.String(length=255, collation="utf8_bin"), nullable=True
        ),
        sa.Column("uid", sa.String(length=255, collation="utf8_bin"), nullable=True),
        sa.Column(
            "producer_uid", sa.String(length=255, collation="utf8_bin"), nullable=True
        ),
        sa.Column("created", mysql.TIMESTAMP(fsp=3), nullable=True),
        sa.Column("updated", mysql.TIMESTAMP(fsp=3), nullable=True),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uid", "project", "key", name="_artifacts_uc"),
    )
    op.create_table(
        "artifacts_labels",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255, collation="utf8_bin"), nullable=True),
        sa.Column("value", sa.String(length=255, collation="utf8_bin"), nullable=True),
        sa.Column("parent", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", "parent", name="_artifacts_labels_uc"),
    )
    op.create_table(
        "artifacts_tags",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8_bin"), nullable=True
        ),
        sa.Column("name", sa.String(length=255, collation="utf8_bin"), nullable=True),
        sa.Column("obj_id", sa.Integer(), nullable=True),
        sa.Column(
            "obj_name", sa.String(length=255, collation="utf8_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["obj_id"],
            ["artifacts.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project", "name", "obj_name", name="_artifacts_tags_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("artifacts_tags")
    op.drop_table("artifacts_labels")
    op.drop_table("artifacts")

    op.rename_table("legacy_artifacts", "artifacts")
    op.rename_table("legacy_artifacts_labels", "artifacts_labels")
    op.rename_table("legacy_artifacts_tags", "artifacts_tags")
    # ### end Alembic commands ###
