"""add_publish_time_to_feature_set

Revision ID: f99d9a10a5c1
Revises: 32bae1b0e29c
Create Date: 2022-06-01 15:22:02.108330

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f99d9a10a5c1"
down_revision = "32bae1b0e29c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "feature_sets", sa.Column("publish_time", sa.TIMESTAMP(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("feature_sets", "publish_time")
    # ### end Alembic commands ###
