# Copyright 2018 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.6-slim
RUN apt-get update && apt-get install -y gcc
RUN pip install --upgrade --no-cache pip pipenv
WORKDIR /mlrun
RUN pip install pipenv
COPY Pipfile* ./
RUN pipenv sync
COPY . .
ENV MLRUN_httpd__dirpath=/mlrun/db
VOLUME /mlrun/db
CMD ["pipenv", "run", "python", "-m", "mlrun.db.httpd"]
