{
 "title": "Model Monitoring - Applications",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "PROJECT", "label": "Project", "query": "target_endpoint=list_projects" },
   {
    "name": "MODELENDPOINT",
    "label": "Model Endpoint",
    "query": "backend=kv;container=users;table=pipelines/$PROJECT/model-endpoints/endpoints;fields=uid;"
   },
   {
    "name": "APPLICATION",
    "label": "Application Name",
    "query": "backend=kv;container=users;table=pipelines/$PROJECT/monitoring-apps/$MODELENDPOINT;fields=__name;"
   }
  ]
 },
 "panels": [
  {
   "title": "# Drift Status by Category",
   "type": "piechart",
   "description": "Pie chart that represents each type of drift result in the selected application.",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;filter= endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  },
  {
   "title": "Average Drift Value Result",
   "type": "gauge",
   "description": "Average drift result value of the provided application in the selected time range.",
   "gridPos": { "h": 9, "w": 8, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;filter= endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  },
  {
   "title": "Latest Result",
   "type": "stat",
   "description": "Latest calculated results according to the selected time range. ",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;filter= endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  },
  {
   "title": "Application Summary",
   "type": "table",
   "description": "Table summary of the application results including the schedule time, the metric name,  metric kind, result status, and result numerical value. ",
   "gridPos": { "h": 10, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;;filter= endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  },
  {
   "title": "Result Value by Time",
   "type": "timeseries",
   "description": "Metric result value by time.",
   "gridPos": { "h": 10, "w": 13, "x": 11, "y": 9 },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;;filter=  endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  },
  {
   "title": "Drift Detection History",
   "type": "timeseries",
   "description": "Drift status by time. Using this chart you can detect different types of drifts by time such as gradual drift or incremental drift. To learn more about different types of drifts, check out Iguazio tutorials:\nhttps://www.iguazio.com/glossary/model-monitoring/\n \nNote that when the result doesn't represent drift (\"irrelevant\"), the value is filtered from this chart. ",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "target": "backend=tsdb;container=users;table=pipelines/$PROJECT/monitoring-apps/app-results;;filter=  endpoint_id=='$MODELENDPOINT' AND application_name ==\"$APPLICATION\";",
     "type": "table"
    }
   ]
  }
 ]
}