// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: proto/log_collector.proto

package log_collector

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// LogCollectorClient is the client API for LogCollector service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LogCollectorClient interface {
	StartLog(ctx context.Context, in *StartLogRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (LogCollector_GetLogsClient, error)
	GetLogSize(ctx context.Context, in *GetLogSizeRequest, opts ...grpc.CallOption) (*GetLogSizeResponse, error)
	StopLogs(ctx context.Context, in *StopLogsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	DeleteLogs(ctx context.Context, in *StopLogsRequest, opts ...grpc.CallOption) (*BaseResponse, error)
	ListRunsInProgress(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (LogCollector_ListRunsInProgressClient, error)
}

type logCollectorClient struct {
	cc grpc.ClientConnInterface
}

func NewLogCollectorClient(cc grpc.ClientConnInterface) LogCollectorClient {
	return &logCollectorClient{cc}
}

func (c *logCollectorClient) StartLog(ctx context.Context, in *StartLogRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/mlrun.LogCollector/StartLog", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) GetLogs(ctx context.Context, in *GetLogsRequest, opts ...grpc.CallOption) (LogCollector_GetLogsClient, error) {
	stream, err := c.cc.NewStream(ctx, &LogCollector_ServiceDesc.Streams[0], "/mlrun.LogCollector/GetLogs", opts...)
	if err != nil {
		return nil, err
	}
	x := &logCollectorGetLogsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogCollector_GetLogsClient interface {
	Recv() (*GetLogsResponse, error)
	grpc.ClientStream
}

type logCollectorGetLogsClient struct {
	grpc.ClientStream
}

func (x *logCollectorGetLogsClient) Recv() (*GetLogsResponse, error) {
	m := new(GetLogsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *logCollectorClient) GetLogSize(ctx context.Context, in *GetLogSizeRequest, opts ...grpc.CallOption) (*GetLogSizeResponse, error) {
	out := new(GetLogSizeResponse)
	err := c.cc.Invoke(ctx, "/mlrun.LogCollector/GetLogSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) StopLogs(ctx context.Context, in *StopLogsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/mlrun.LogCollector/StopLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) DeleteLogs(ctx context.Context, in *StopLogsRequest, opts ...grpc.CallOption) (*BaseResponse, error) {
	out := new(BaseResponse)
	err := c.cc.Invoke(ctx, "/mlrun.LogCollector/DeleteLogs", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *logCollectorClient) ListRunsInProgress(ctx context.Context, in *ListRunsRequest, opts ...grpc.CallOption) (LogCollector_ListRunsInProgressClient, error) {
	stream, err := c.cc.NewStream(ctx, &LogCollector_ServiceDesc.Streams[1], "/mlrun.LogCollector/ListRunsInProgress", opts...)
	if err != nil {
		return nil, err
	}
	x := &logCollectorListRunsInProgressClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type LogCollector_ListRunsInProgressClient interface {
	Recv() (*ListRunsResponse, error)
	grpc.ClientStream
}

type logCollectorListRunsInProgressClient struct {
	grpc.ClientStream
}

func (x *logCollectorListRunsInProgressClient) Recv() (*ListRunsResponse, error) {
	m := new(ListRunsResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// LogCollectorServer is the server API for LogCollector service.
// All implementations should embed UnimplementedLogCollectorServer
// for forward compatibility
type LogCollectorServer interface {
	StartLog(context.Context, *StartLogRequest) (*BaseResponse, error)
	GetLogs(*GetLogsRequest, LogCollector_GetLogsServer) error
	GetLogSize(context.Context, *GetLogSizeRequest) (*GetLogSizeResponse, error)
	StopLogs(context.Context, *StopLogsRequest) (*BaseResponse, error)
	DeleteLogs(context.Context, *StopLogsRequest) (*BaseResponse, error)
	ListRunsInProgress(*ListRunsRequest, LogCollector_ListRunsInProgressServer) error
}

// UnimplementedLogCollectorServer should be embedded to have forward compatible implementations.
type UnimplementedLogCollectorServer struct {
}

func (UnimplementedLogCollectorServer) StartLog(context.Context, *StartLogRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartLog not implemented")
}
func (UnimplementedLogCollectorServer) GetLogs(*GetLogsRequest, LogCollector_GetLogsServer) error {
	return status.Errorf(codes.Unimplemented, "method GetLogs not implemented")
}
func (UnimplementedLogCollectorServer) GetLogSize(context.Context, *GetLogSizeRequest) (*GetLogSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLogSize not implemented")
}
func (UnimplementedLogCollectorServer) StopLogs(context.Context, *StopLogsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopLogs not implemented")
}
func (UnimplementedLogCollectorServer) DeleteLogs(context.Context, *StopLogsRequest) (*BaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteLogs not implemented")
}
func (UnimplementedLogCollectorServer) ListRunsInProgress(*ListRunsRequest, LogCollector_ListRunsInProgressServer) error {
	return status.Errorf(codes.Unimplemented, "method ListRunsInProgress not implemented")
}

// UnsafeLogCollectorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LogCollectorServer will
// result in compilation errors.
type UnsafeLogCollectorServer interface {
	mustEmbedUnimplementedLogCollectorServer()
}

func RegisterLogCollectorServer(s grpc.ServiceRegistrar, srv LogCollectorServer) {
	s.RegisterService(&LogCollector_ServiceDesc, srv)
}

func _LogCollector_StartLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartLogRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).StartLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlrun.LogCollector/StartLog",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).StartLog(ctx, req.(*StartLogRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_GetLogs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetLogsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogCollectorServer).GetLogs(m, &logCollectorGetLogsServer{stream})
}

type LogCollector_GetLogsServer interface {
	Send(*GetLogsResponse) error
	grpc.ServerStream
}

type logCollectorGetLogsServer struct {
	grpc.ServerStream
}

func (x *logCollectorGetLogsServer) Send(m *GetLogsResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _LogCollector_GetLogSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLogSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).GetLogSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlrun.LogCollector/GetLogSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).GetLogSize(ctx, req.(*GetLogSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_StopLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).StopLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlrun.LogCollector/StopLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).StopLogs(ctx, req.(*StopLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_DeleteLogs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopLogsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LogCollectorServer).DeleteLogs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/mlrun.LogCollector/DeleteLogs",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LogCollectorServer).DeleteLogs(ctx, req.(*StopLogsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LogCollector_ListRunsInProgress_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListRunsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LogCollectorServer).ListRunsInProgress(m, &logCollectorListRunsInProgressServer{stream})
}

type LogCollector_ListRunsInProgressServer interface {
	Send(*ListRunsResponse) error
	grpc.ServerStream
}

type logCollectorListRunsInProgressServer struct {
	grpc.ServerStream
}

func (x *logCollectorListRunsInProgressServer) Send(m *ListRunsResponse) error {
	return x.ServerStream.SendMsg(m)
}

// LogCollector_ServiceDesc is the grpc.ServiceDesc for LogCollector service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LogCollector_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "mlrun.LogCollector",
	HandlerType: (*LogCollectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartLog",
			Handler:    _LogCollector_StartLog_Handler,
		},
		{
			MethodName: "GetLogSize",
			Handler:    _LogCollector_GetLogSize_Handler,
		},
		{
			MethodName: "StopLogs",
			Handler:    _LogCollector_StopLogs_Handler,
		},
		{
			MethodName: "DeleteLogs",
			Handler:    _LogCollector_DeleteLogs_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetLogs",
			Handler:       _LogCollector_GetLogs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListRunsInProgress",
			Handler:       _LogCollector_ListRunsInProgress_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/log_collector.proto",
}
