# Copyright 2025 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import os
from unittest.mock import Mock

import pytest

import mlrun.common.schemas.model_monitoring as mm_schemas
from mlrun.model_monitoring.db.tsdb.timescaledb.timescaledb_query_handler import (
    TimescaleDBQueryHandler,
)

# Skip entire module if connection string is not available or not PostgreSQL
connection_string = os.getenv("MLRUN_MODEL_ENDPOINT_MONITORING__TSDB_CONNECTION")
pytestmark = pytest.mark.skipif(
    not connection_string or not connection_string.startswith("postgres"),
    reason="TimescaleDB connection string not available or not PostgreSQL",
)


class TestTimescaleDBQueryHandlerInitialization:
    """Test TimescaleDB query handler initialization and configuration."""

    def test_constructor_initialization(self):
        """Test TimescaleDBQueryHandler constructor initializes correctly."""
        mock_connection = Mock()
        mock_config = Mock()

        handler = TimescaleDBQueryHandler(
            project="test_project",
            connection=mock_connection,
            pre_aggregate_config=mock_config,
        )

        # Verify initialization
        assert handler.project == "test_project"
        assert handler._connection == mock_connection
        assert handler._pre_aggregate_config == mock_config

        # Verify tables were initialized
        assert mm_schemas.TimescaleDBTables.APP_RESULTS in handler.tables
        assert mm_schemas.TimescaleDBTables.METRICS in handler.tables
        assert mm_schemas.TimescaleDBTables.PREDICTIONS in handler.tables
        assert mm_schemas.TimescaleDBTables.ERRORS in handler.tables

        # Verify each table has correct project and schema
        for table in handler.tables.values():
            assert table.project == "test_project"
            assert table.schema == handler.schema

    def test_initialization_with_operations(self, query_handler):
        """Test proper initialization of TimescaleDBQueryHandler with operations."""
        # Use the query_handler fixture instead of creating the handler manually
        handler = query_handler

        assert handler.project is not None  # Project name is generated by fixture
        assert handler._pre_aggregate_config is None
        assert hasattr(handler, "tables")
        assert len(handler.tables) == 4  # APP_RESULTS, METRICS, PREDICTIONS, ERRORS

    def test_get_preaggregate_config(self, query_handler):
        """Test get_preaggregate_config returns the configured pre-aggregate config."""
        config = query_handler.get_preaggregate_config()

        # Should return the pre-aggregate config (could be None for basic test setup)
        assert config is query_handler._pre_aggregate_config

    def test_schema_property(self, query_handler):
        """Test that schema property returns expected schema name."""
        schema = query_handler.schema

        # Should include system ID in schema name
        assert "model_monitoring" in schema
        assert isinstance(schema, str)
        assert len(schema) > 0

    def test_tables_property(self, query_handler):
        """Test that tables property contains all expected tables."""
        tables = query_handler.tables

        assert isinstance(tables, dict)
        assert len(tables) == 4

        # Check all required table types exist
        expected_tables = [
            mm_schemas.TimescaleDBTables.APP_RESULTS,
            mm_schemas.TimescaleDBTables.METRICS,
            mm_schemas.TimescaleDBTables.PREDICTIONS,
            mm_schemas.TimescaleDBTables.ERRORS,
        ]

        for table_type in expected_tables:
            assert table_type in tables
            table = tables[table_type]
            assert hasattr(table, "table_name")
            assert hasattr(table, "schema")
            assert hasattr(table, "project")
