"""Background task error message

Revision ID: 041e055100b4
Revises: 27ed4ecb734c
Create Date: 2023-11-06 09:07:13.211984

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "041e055100b4"
down_revision = "27ed4ecb734c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "background_tasks",
        sa.Column("error", sa.String(length=255, collation="utf8_bin"), nullable=True),
    )
    op.drop_index("_feature_sets_tags_obj_name_fk", table_name="feature_sets_tags")
    op.drop_index(
        "_feature_vectors_tags_obj_name_fk", table_name="feature_vectors_tags"
    )
    op.drop_index("_functions_tags_obj_name_fk", table_name="functions_tags")
    op.drop_index("_marketplace_sources_uc", table_name="hub_sources")
    op.create_unique_constraint("_hub_sources_uc", "hub_sources", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_hub_sources_uc", "hub_sources", type_="unique")
    op.create_index("_marketplace_sources_uc", "hub_sources", ["name"], unique=False)
    op.create_index(
        "_functions_tags_obj_name_fk", "functions_tags", ["obj_name"], unique=False
    )
    op.create_index(
        "_feature_vectors_tags_obj_name_fk",
        "feature_vectors_tags",
        ["obj_name"],
        unique=False,
    )
    op.create_index(
        "_feature_sets_tags_obj_name_fk",
        "feature_sets_tags",
        ["obj_name"],
        unique=False,
    )
    op.drop_column("background_tasks", "error")
    # ### end Alembic commands ###
