# Copyright 2023 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""market_place_to_hub

Revision ID: 28383af526f3
Revises: c905d15bd91d
Create Date: 2023-04-24 11:06:36.177314

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "28383af526f3"
down_revision = "c905d15bd91d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("marketplace_sources", "hub_sources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table("hub_sources", "marketplace_sources")
    # ### end Alembic commands ###
