"""add default function node selector to project

Revision ID: 68dadc9d9bc8
Revises: c0e342d73bd0
Create Date: 2024-03-18 17:57:10.264336

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "68dadc9d9bc8"
down_revision = "c0e342d73bd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("default_function_node_selector", sa.JSON(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("projects", "default_function_node_selector")
    # ### end Alembic commands ###
