"""Index ArtifactsV2 fields

Revision ID: b0f0e8844152
Revises: c0e342d73bd0
Create Date: 2024-06-10 11:09:47.659848

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b0f0e8844152"
down_revision = "c0e342d73bd0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_artifacts_v2_iteration"), "artifacts_v2", ["iteration"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_v2_producer_id"),
        "artifacts_v2",
        ["producer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifacts_v2_project"), "artifacts_v2", ["project"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_v2_project"), table_name="artifacts_v2")
    op.drop_index(op.f("ix_artifacts_v2_producer_id"), table_name="artifacts_v2")
    op.drop_index(op.f("ix_artifacts_v2_iteration"), table_name="artifacts_v2")
    # ### end Alembic commands ###
