"""Background task error message

Revision ID: b899cbf87203
Revises: 59061f6e2a87
Create Date: 2023-11-08 10:59:06.391117

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b899cbf87203"
down_revision = "59061f6e2a87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "background_tasks",
        sa.Column("error", sa.String(length=255, collation="utf8_bin"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("background_tasks", "error")
    # ### end Alembic commands ###
