"""indexing artifact_v2 key

Revision ID: c0e342d73bd0
Revises: b268044fa2f7
Create Date: 2024-02-07 14:46:55.639228

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "c0e342d73bd0"
down_revision = "b268044fa2f7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_artifacts_v2_key"), "artifacts_v2", ["key"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_v2_key"), table_name="artifacts_v2")
    # ### end Alembic commands ###
