"""Index artifacts_v2_tags fields

Revision ID: d646801e30ef
Revises: aa28cdc5bb17
Create Date: 2024-06-18 19:19:47.343182

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "d646801e30ef"
down_revision = "aa28cdc5bb17"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_artifacts_v2_tags_project_name_obj_name",
        "artifacts_v2_tags",
        ["project", "name", "obj_name"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_artifacts_v2_tags_project_name_obj_name",
        table_name="artifacts_v2_tags",
    )
    # ### end Alembic commands ###
