"""Index ArtifactsV2 fields

Revision ID: 311d8cbc42a9
Revises: cfe2a22173fc
Create Date: 2024-06-16 16:00:33.418577

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "311d8cbc42a9"
down_revision = "cfe2a22173fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_artifacts_producer_id_best_iteration_and_project",
        "artifacts_v2",
        ["project", "producer_id", "best_iteration"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "idx_artifacts_producer_id_best_iteration_and_project",
        table_name="artifacts_v2",
    )
    # ### end Alembic commands ###
