"""add alert history

Revision ID: 38b2f0b84eef
Revises: fcf2ea01f99a
Create Date: 2024-10-29 18:10:32.458406

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '38b2f0b84eef'
down_revision = 'fcf2ea01f99a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('activation_time', mysql.DATETIME(timezone=True, fsp=3), nullable=False),
    sa.Column('name', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('project', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('entity_id', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('entity_kind', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('event_kind', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('severity', sa.String(length=255, collation='utf8mb3_bin'), nullable=False),
    sa.Column('number_of_events', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('activation_time', 'id', name='_alert_history_uc')
    )
    # ### end Alembic commands ###

    # Add initial partitioning
    partition_interval = os.getenv('PARTITION_INTERVAL', 'YEARWEEK')
    default_partition_value = os.getenv('DEFAULT_PARTITION_VALUE', '2023-01-01')
    partition_sql = f"""
        ALTER TABLE alert_history
        PARTITION BY RANGE ({partition_interval}(activation_time)) (
            PARTITION p0 VALUES LESS THAN ({partition_interval}('{default_partition_value}'))
        );
    """
    op.execute(partition_sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alert_history')
    # ### end Alembic commands ###
