# Copyright 2023 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Cascade delete labels and tags

Revision ID: 53dc14352833
Revises: fcf2ea01f99a
Create Date: 2024-10-29 16:38:14.588933

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "53dc14352833"
down_revision = "fcf2ea01f99a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "artifacts_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_artifacts_labels_uc", "artifacts_labels", type_="unique")
    op.create_unique_constraint(
        "_artifacts_labels_uc", "artifacts_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_artifacts_labels_paren_fk", "artifacts_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "artifacts_labels", "artifacts", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("artifacts_labels", "parent")
    op.add_column(
        "artifacts_v2_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_artifacts_v2_labels_uc", "artifacts_v2_labels", type_="unique")
    op.create_unique_constraint(
        "_artifacts_v2_labels_uc", "artifacts_v2_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "artifacts_v2_labels_ibfk_1", "artifacts_v2_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "artifacts_v2_labels",
        "artifacts_v2",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("artifacts_v2_labels", "parent")
    op.drop_constraint(
        "artifacts_v2_tags_ibfk_1", "artifacts_v2_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "artifacts_v2_tags",
        "artifacts_v2",
        ["obj_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "entities_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_entities_labels_uc", "entities_labels", type_="unique")
    op.create_unique_constraint(
        "_entities_labels_uc", "entities_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_entities_labels_parent_fk", "entities_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "entities_labels", "entities", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("entities_labels", "parent")
    op.add_column(
        "feature_sets_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_feature_sets_labels_uc", "feature_sets_labels", type_="unique")
    op.create_unique_constraint(
        "_feature_sets_labels_uc", "feature_sets_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_feature_sets_labels_parent_fk", "feature_sets_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "feature_sets_labels",
        "feature_sets",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("feature_sets_labels", "parent")
    op.drop_constraint(
        "_feature_sets_tags_obj_id_fk", "feature_sets_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "feature_sets_tags",
        "feature_sets",
        ["obj_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "feature_vectors_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint(
        "_feature_vectors_labels_uc", "feature_vectors_labels", type_="unique"
    )
    op.create_unique_constraint(
        "_feature_vectors_labels_uc", "feature_vectors_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_feature_vectors_labels_parent_fk",
        "feature_vectors_labels",
        type_="foreignkey",
    )
    op.create_foreign_key(
        None,
        "feature_vectors_labels",
        "feature_vectors",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("feature_vectors_labels", "parent")
    op.drop_constraint(
        "_feature_vectors_tags_obj_id_fk", "feature_vectors_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "feature_vectors_tags",
        "feature_vectors",
        ["obj_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.add_column(
        "features_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_features_labels_uc", "features_labels", type_="unique")
    op.create_unique_constraint(
        "_features_labels_uc", "features_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_features_labels_parent_fk", "features_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "features_labels", "features", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("features_labels", "parent")
    op.add_column(
        "functions_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_functions_labels_uc", "functions_labels", type_="unique")
    op.create_unique_constraint(
        "_functions_labels_uc", "functions_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_functions_labels_parent_fk", "functions_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "functions_labels", "functions", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("functions_labels", "parent")
    op.drop_constraint(
        "_functions_tags_obj_id_fk", "functions_tags", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "functions_tags", "functions", ["obj_id"], ["id"], ondelete="CASCADE"
    )
    op.add_column(
        "projects_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_projects_labels_uc", "projects_labels", type_="unique")
    op.create_unique_constraint(
        "_projects_labels_uc", "projects_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_projects_labels_parent_fk", "projects_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "projects_labels", "projects", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("projects_labels", "parent")
    op.add_column("runs_labels", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.drop_constraint("_runs_labels_uc", "runs_labels", type_="unique")
    op.create_unique_constraint("_runs_labels_uc", "runs_labels", ["name", "parent_id"])
    op.drop_constraint("_runs_labels_parent_fk", "runs_labels", type_="foreignkey")
    op.create_foreign_key(
        None, "runs_labels", "runs", ["parent_id"], ["id"], ondelete="CASCADE"
    )
    op.drop_column("runs_labels", "parent")
    op.add_column(
        "schedules_v2_labels", sa.Column("parent_id", sa.Integer(), nullable=True)
    )
    op.drop_constraint("_schedules_v2_labels_uc", "schedules_v2_labels", type_="unique")
    op.create_unique_constraint(
        "_schedules_v2_labels_uc", "schedules_v2_labels", ["name", "parent_id"]
    )
    op.drop_constraint(
        "_schedules_v2_labels_parent_fk", "schedules_v2_labels", type_="foreignkey"
    )
    op.create_foreign_key(
        None,
        "schedules_v2_labels",
        "schedules_v2",
        ["parent_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_column("schedules_v2_labels", "parent")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "schedules_v2_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "schedules_v2_labels", type_="foreignkey")
    op.create_foreign_key(
        "_schedules_v2_labels_parent_fk",
        "schedules_v2_labels",
        "schedules_v2",
        ["parent"],
        ["id"],
    )
    op.drop_constraint("_schedules_v2_labels_uc", "schedules_v2_labels", type_="unique")
    op.create_unique_constraint(
        "_schedules_v2_labels_uc", "schedules_v2_labels", ["name", "parent"]
    )
    op.drop_column("schedules_v2_labels", "parent_id")
    op.add_column(
        "runs_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "runs_labels", type_="foreignkey")
    op.create_foreign_key(
        "_runs_labels_parent_fk", "runs_labels", "runs", ["parent"], ["id"]
    )
    op.drop_constraint("_runs_labels_uc", "runs_labels", type_="unique")
    op.create_unique_constraint("_runs_labels_uc", "runs_labels", ["name", "parent"])
    op.drop_column("runs_labels", "parent_id")
    op.add_column(
        "projects_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "projects_labels", type_="foreignkey")
    op.create_foreign_key(
        "_projects_labels_parent_fk", "projects_labels", "projects", ["parent"], ["id"]
    )
    op.drop_constraint("_projects_labels_uc", "projects_labels", type_="unique")
    op.create_unique_constraint(
        "_projects_labels_uc", "projects_labels", ["name", "parent"]
    )
    op.drop_column("projects_labels", "parent_id")
    op.drop_constraint(None, "functions_tags", type_="foreignkey")
    op.create_foreign_key(
        "_functions_tags_obj_id_fk", "functions_tags", "functions", ["obj_id"], ["id"]
    )
    op.add_column(
        "functions_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "functions_labels", type_="foreignkey")
    op.create_foreign_key(
        "_functions_labels_parent_fk",
        "functions_labels",
        "functions",
        ["parent"],
        ["id"],
    )
    op.drop_constraint("_functions_labels_uc", "functions_labels", type_="unique")
    op.create_unique_constraint(
        "_functions_labels_uc", "functions_labels", ["name", "parent"]
    )
    op.drop_column("functions_labels", "parent_id")
    op.add_column(
        "features_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "features_labels", type_="foreignkey")
    op.create_foreign_key(
        "_features_labels_parent_fk", "features_labels", "features", ["parent"], ["id"]
    )
    op.drop_constraint("_features_labels_uc", "features_labels", type_="unique")
    op.create_unique_constraint(
        "_features_labels_uc", "features_labels", ["name", "parent"]
    )
    op.drop_column("features_labels", "parent_id")
    op.drop_constraint(None, "feature_vectors_tags", type_="foreignkey")
    op.create_foreign_key(
        "_feature_vectors_tags_obj_id_fk",
        "feature_vectors_tags",
        "feature_vectors",
        ["obj_id"],
        ["id"],
    )
    op.add_column(
        "feature_vectors_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "feature_vectors_labels", type_="foreignkey")
    op.create_foreign_key(
        "_feature_vectors_labels_parent_fk",
        "feature_vectors_labels",
        "feature_vectors",
        ["parent"],
        ["id"],
    )
    op.drop_constraint(
        "_feature_vectors_labels_uc", "feature_vectors_labels", type_="unique"
    )
    op.create_unique_constraint(
        "_feature_vectors_labels_uc", "feature_vectors_labels", ["name", "parent"]
    )
    op.drop_column("feature_vectors_labels", "parent_id")
    op.drop_constraint(None, "feature_sets_tags", type_="foreignkey")
    op.create_foreign_key(
        "_feature_sets_tags_obj_id_fk",
        "feature_sets_tags",
        "feature_sets",
        ["obj_id"],
        ["id"],
    )
    op.add_column(
        "feature_sets_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "feature_sets_labels", type_="foreignkey")
    op.create_foreign_key(
        "_feature_sets_labels_parent_fk",
        "feature_sets_labels",
        "feature_sets",
        ["parent"],
        ["id"],
    )
    op.drop_constraint("_feature_sets_labels_uc", "feature_sets_labels", type_="unique")
    op.create_unique_constraint(
        "_feature_sets_labels_uc", "feature_sets_labels", ["name", "parent"]
    )
    op.drop_column("feature_sets_labels", "parent_id")
    op.add_column(
        "entities_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "entities_labels", type_="foreignkey")
    op.create_foreign_key(
        "_entities_labels_parent_fk", "entities_labels", "entities", ["parent"], ["id"]
    )
    op.drop_constraint("_entities_labels_uc", "entities_labels", type_="unique")
    op.create_unique_constraint(
        "_entities_labels_uc", "entities_labels", ["name", "parent"]
    )
    op.drop_column("entities_labels", "parent_id")
    op.drop_constraint(None, "artifacts_v2_tags", type_="foreignkey")
    op.create_foreign_key(
        "artifacts_v2_tags_ibfk_1",
        "artifacts_v2_tags",
        "artifacts_v2",
        ["obj_id"],
        ["id"],
    )
    op.add_column(
        "artifacts_v2_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "artifacts_v2_labels", type_="foreignkey")
    op.create_foreign_key(
        "artifacts_v2_labels_ibfk_1",
        "artifacts_v2_labels",
        "artifacts_v2",
        ["parent"],
        ["id"],
    )
    op.drop_constraint("_artifacts_v2_labels_uc", "artifacts_v2_labels", type_="unique")
    op.create_unique_constraint(
        "_artifacts_v2_labels_uc", "artifacts_v2_labels", ["name", "parent"]
    )
    op.drop_column("artifacts_v2_labels", "parent_id")
    op.add_column(
        "artifacts_labels",
        sa.Column("parent", mysql.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "artifacts_labels", type_="foreignkey")
    op.create_foreign_key(
        "_artifacts_labels_paren_fk",
        "artifacts_labels",
        "artifacts",
        ["parent"],
        ["id"],
    )
    op.drop_constraint("_artifacts_labels_uc", "artifacts_labels", type_="unique")
    op.create_unique_constraint(
        "_artifacts_labels_uc", "artifacts_labels", ["name", "parent"]
    )
    op.drop_column("artifacts_labels", "parent_id")
    # ### end Alembic commands ###
