"""add alert history

Revision ID: 650f0ce2da6f
Revises: fcf2ea01f99a
Create Date: 2024-10-30 16:38:07.592754

"""

import os
from datetime import datetime

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "650f0ce2da6f"
down_revision = "fcf2ea01f99a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "alert_history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "activation_time", mysql.DATETIME(timezone=True, fsp=3), nullable=False
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.Column(
            "entity_id", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "entity_kind",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=False,
        ),
        sa.Column(
            "event_kind", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "severity", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("number_of_events", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("activation_time", "id", name="_alert_history_uc"),
    )
    op.create_index(
        "ix_alert_history_activation_time",
        "alert_history",
        ["activation_time"],
        unique=False,
    )
    op.create_index(
        "ix_alert_history_project_name",
        "alert_history",
        ["project", "name"],
        unique=False,
    )
    # ### end Alembic commands ###

    partition_interval = os.getenv("PARTITION_INTERVAL", "DAY").upper()
    valid_partition_intervals = ["DAY", "YEARWEEK", "MONTH"]

    # Validate the partition interval
    if partition_interval not in valid_partition_intervals:
        raise ValueError(
            f"Partition interval can only be one of the following: {valid_partition_intervals}"
        )

    # Current UTC date
    now_utc = datetime.utcnow()

    # Define partition name format based on interval
    partition_name_format_mapping = {
        "YEARWEEK": "%Y%V",  # ISO week number (for weeks starting Monday)
        "MONTH": "%Y%m",  # Format as 'YYYYMM' (year and month)
        "DAY": "%Y%m%d",  # Format as 'YYYYMMDD' (year, month, day)
    }

    # Generate the partition name
    partition_name = now_utc.strftime(partition_name_format_mapping[partition_interval])

    # Calculate partition value depending on interval
    if partition_interval == "YEARWEEK":
        partition_value = int(
            now_utc.strftime("%Y%V")
        )  # Example: 202444 for 44th week of 2024
        partition_expression = "YEARWEEK(activation_time, 1)"
    else:
        partition_value = now_utc.strftime("%Y-%m-%d")
        partition_expression = f"{partition_interval}(activation_time)"

    # Construct SQL for partitioning
    partition_sql = f"""
        ALTER TABLE alert_history
        PARTITION BY RANGE ({partition_expression}) (
            PARTITION p{partition_name} VALUES LESS THAN ({partition_value})
        );
    """

    # Execute the SQL command
    op.execute(partition_sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("alert_history")
    # ### end Alembic commands ###
