# Copyright 2023 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Added Foo to FunctionSpec

Revision ID: b4b61049cbe9
Revises: fcf2ea01f99a
Create Date: 2024-09-04 11:24:00.385881

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b4b61049cbe9"
down_revision = "fcf2ea01f99a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "function_spec_foos",
        sa.Column(
            "data", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("function_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["function_id"], ["functions.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("function_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("function_spec_foos")
    # ### end Alembic commands ###
