"""add project summary table

Revision ID: b746b831d06c
Revises: cfe2a22173fc
Create Date: 2024-07-09 11:27:28.255723

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b746b831d06c"
down_revision = "cfe2a22173fc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "project_summaries",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("summary", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project", name="_project_summaries_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("project_summaries")
    # ### end Alembic commands ###
