# Copyright 2023 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""Background task error message

Revision ID: b899cbf87203
Revises: 59061f6e2a87
Create Date: 2023-11-08 10:59:06.391117

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "b899cbf87203"
down_revision = "59061f6e2a87"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "background_tasks",
        sa.Column("error", sa.String(length=255, collation="utf8_bin"), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("background_tasks", "error")
    # ### end Alembic commands ###
