name: Bug Report
description: Report incorrect behavior in MLRun CE
title: "[Bug]: "

body:
  - type: checkboxes
    id: checks
    attributes:
      label: MLRun Version checks
      options:
        - label: >
            I have checked that this issue has not already been reported.
          required: true
        - label: >
            I have confirmed this bug exists on the latest version of MLRun CE.
          required: true
  - type: textarea
    id: example
    attributes:
      label: Reproducible Example
      description: >
        If you are running an existing example/demo, please link it here. Otherwise please follow [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) on how to
        provide a minimal, copy-pastable example.
      placeholder: >
        import mlrun

        ...
      render: python
    validations:
      required: true
  - type: textarea
    id: problem
    attributes:
      label: Issue Description
      description: >
        Please provide a description of the issue shown in the reproducible example.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: >
        Please describe or show a code example of the expected behavior.
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Installation OS
      description: >
        Please provide the OS you are installing on.
      options:
        - Mac
        - Windows
        - Linux
        - Other
    validations:
      required: true
  - type: dropdown
    id: method
    attributes:
      label: Installation Method
      description: >
        Please provide how you tried to install MLRun.
      options:
        - Docker
        - Kubernetes
        - CloudFormation
    validations:
      required: true
  - type: input
    id: python_version
    attributes:
      label: Python Version
      description: >
        Please paste the output of ``import platform; platform.python_version()``
    validations:
      required: true
  - type: input
    id: mlrun_version
    attributes:
      label: MLRun Version
      description: >
        Please paste the output of ``import mlrun; mlrun.get_version()``
    validations:
      required: true
  - type: textarea
    id: additional_information
    attributes:
      label: Additional Information
      description: >
        Please add any aditional information you think may be relevant.
