kind: project
metadata:
  name: breast-cancer-admin
spec:
  functions:
  - url: gen_breast_cancer.py
    name: gen-breast-cancer
    image: mlrun/mlrun
  - url: trainer.py
    name: trainer
    image: mlrun/mlrun
    handler: train
  - url: serving.py
    name: serving
    kind: serving
    image: mlrun/mlrun
  workflows: []
  artifacts: []
  source: git://github.com/yaronha/tutorial.git#refs/heads/main
  subpath: ''
  origin_url: git://github.com/yaronha/tutorial.git#refs/heads/main
  desired_state: online
  disable_auto_mount: false
