# Copyright 2018 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM python:3.7-slim
RUN apt-get update && apt-get install -y g++ make git-core
RUN python -m pip install --upgrade --no-cache pip
WORKDIR /mlrun

COPY ./requirements.txt ./
COPY ./dockerfiles/mlrun-api/requirements.txt ./mlrun-api-requirements.txt

RUN pip install \
    -r requirements.txt \
    -r mlrun-api-requirements.txt

# if we give all the requirements together pip resolver go nuts so separating between the package and the image
# requirements
COPY ./dev-requirements.txt ./
RUN python -m pip install \
    -r dev-requirements.txt

COPY . .
ENV PYTHONPATH=/mlrun
RUN python -m pip install .
{args}
{pip}
RUN jupyter nbconvert --ExecutePreprocessor.timeout=600 --execute {notebook}
