apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlrun-ui
  labels:
    app: mlrun-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlrun-ui
  template:
    metadata:
      labels:
        app: mlrun-ui
    spec:
      containers:
      - name: mlrun-ui
        image: quay.io/iguazio/mlrun-frontend
        imagePullPolicy: Always
        env:
        - name: MLRUN_API_BASE_URL
          value: http://<mlrun-api-external-ip>:30080/api
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1
metadata:
  name: mlrun-ui
spec:
  type: NodePort
  selector:
    app: mlrun-ui
  ports:
  - protocol: TCP
    nodePort: 30088
    port: 80
    targetPort: 80
