# example Kubernetes spec, should add volume for persisting data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlrun-api
  labels:
    app: mlrun-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlrun-api
  template:
    metadata:
      labels:
        app: mlrun-api
    spec:
      containers:
      - name: mlrun-api
        image: mlrun/mlrun-api:latest
        imagePullPolicy: Always
        env:
        - name: MLRUN_HTTPDB__DIRPATH
          value: "/mlrun/db"
        - name: DEFAULT_DOCKER_REGISTRY
          value: "<set default registry url>"
        - name: MLRUN_HTTPDB__DSN
          value: sqlite:///mlrun.sqlite3?check_same_thread=false
        - name: V3IO_ACCESS_KEY
          value: <access-key>
        - name: V3IO_USERNAME
          value: admin
        ports:
        - containerPort: 8080
        command: ["python", "-m", "mlrun", "db"]
        args: []
# UNCOMMENT TO ADD V3IO VOLUME + SET ACCESS KEY
#        volumeMounts:
#        - mountPath: /mlrun/db
#          name: fs
#      volumes:
#      - flexVolume:
#          driver: v3io/fuse
#          options:
#            accessKey: <access-key>
#            container: users
#            subPath: /admin
#        name: fs
      serviceAccountName: mlrun-api
---
kind: Service
apiVersion: v1
metadata:
  name: mlrun-api
spec:
  type: NodePort
  selector:
    app: mlrun-api
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlrun-api
  namespace: default-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlrun-api-role
  namespace: default-tenant
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - services
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - '*'
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlrun-api-binding
  namespace: default-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlrun-api-role
subjects:
- kind: ServiceAccount
  name: mlrun-api
  namespace: default-tenant
