# example Kubernetes spec, should add volume for persisting data
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlrun-api
  labels:
    app: mlrun-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlrun-api
  template:
    metadata:
      labels:
        app: mlrun-api
    spec:
      containers:
      - name: mlrun-api
        image: mlrun/mlrun-api:1.0.6
        env:
        - name: MLRUN_HTTPDB__BUILDER__DOCKER_REGISTRY
          value: "default registry url e.g. index.docker.io/<username>, if repository is not set it will default to mlrun"
# Uncomment to use a secret when accessing Dockerhub
#        - name: MLRUN_HTTPDB__BUILDER__DOCKER_REGISTRY_SECRET
#          value: my-docker
        - name: MLRUN_HTTPDB__API_URL
          value: "http://mlrun-api:8080"
        - name: V3IO_ACCESS_KEY
          value: <access-key>
        - name: V3IO_USERNAME
          value: admin
        - name: MLRUN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
# Uncomment to enable Vault secrets integration
#        - name: MLRUN_SECRET_STORES__VAULT__URL
#          value: 'Your Vault URL here'
#        - name: MLRUN_SECRET_STORES__VAULT__ROLE
#          value: 'user:mlrun-api'
        ports:
        - containerPort: 8080
# UNCOMMENT TO ADD V3IO VOLUME + SET ACCESS KEY
#        volumeMounts:
#        - mountPath: /mlrun/db
#          name: storage
#      volumes:
#      - flexVolume:
#          driver: v3io/fuse
#          options:
#            accessKey: <access-key>
#            container: users
#            subPath: /admin
#        name: storage
      serviceAccountName: mlrun-api
---
kind: Service
apiVersion: v1
metadata:
  name: mlrun-api
spec:
  type: NodePort
  selector:
    app: mlrun-api
  ports:
  - protocol: TCP
    nodePort: 30080
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: mlrun-api
  namespace: default-tenant
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: mlrun-api-role
  namespace: default-tenant
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - pods/log
  - services
  - serviceaccounts
  - secrets
  verbs:
  - '*'
- apiGroups:
  - kubeflow.org
  resources:
  - mpijobs
  verbs:
  - '*'
- apiGroups:
  - sparkoperator.k8s.io
  resources:
  - sparkapplications
  - scheduledsparkapplications
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mlrun-api-binding
  namespace: default-tenant
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: mlrun-api-role
subjects:
- kind: ServiceAccount
  name: mlrun-api
  namespace: default-tenant
