"""market_place_to_hub

Revision ID: 4acd9430b093
Revises: 959ae00528ad
Create Date: 2023-04-26 22:41:59.726305

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '4acd9430b093'
down_revision = '959ae00528ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("marketplace_sources") as batch_op:
        batch_op.rename_table("hub_sources")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("hub_sources") as batch_op:
        batch_op.rename_table('hub_sources', "marketplace_sources")
    # ### end Alembic commands ###
