"""adding next_run_time column to schedule table

Revision ID: 6401142f2d7c
Revises: 64d90a1a69bc
Create Date: 2022-08-16 17:51:41.624145

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6401142f2d7c"
down_revision = "64d90a1a69bc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules_v2") as batch_op:
        batch_op.add_column(sa.Column("next_run_time", sa.TIMESTAMP(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("schedules_v2") as batch_op:
        batch_op.drop_column("next_run_time")
    # ### end Alembic commands ###
