"""Adding background task table

Revision ID: 70651978f117
Revises: e5594ed3ab53
Create Date: 2022-06-01 10:09:25.658580

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "70651978f117"
down_revision = "e5594ed3ab53"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "background_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("project", sa.String(length=255), nullable=True),
        sa.Column("created", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated", sa.TIMESTAMP(), nullable=True),
        sa.Column("state", sa.String(length=255), nullable=True),
        sa.Column("timeout", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("background_task")
    # ### end Alembic commands ###
