"""add requested_logs column to runs

Revision ID: 803438ecd005
Revises: 6401142f2d7c
Create Date: 2023-01-11 10:31:18.505231

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "803438ecd005"
down_revision = "6401142f2d7c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.add_column(sa.Column("requested_logs", sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.drop_column("requested_logs")
    # ### end Alembic commands ###
