"""Adding name and updated to runs table

Revision ID: e5594ed3ab53
Revises: accf9fc83d38
Create Date: 2022-01-08 12:33:59.070265

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5594ed3ab53'
down_revision = 'accf9fc83d38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.add_column(sa.Column("name", sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column("updated", sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("runs") as batch_op:
        batch_op.drop_column("name")
        batch_op.drop_column("updated")
    # ### end Alembic commands ###
