# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/log_collector.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/log_collector.proto',
  package='mlrun',
  syntax='proto3',
  serialized_options=b'Z\031proto/build/log_collector',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19proto/log_collector.proto\x12\x05mlrun\x1a\x1bgoogle/protobuf/empty.proto\"\x89\x01\n\x0fStartLogRequest\x12\r\n\x05runId\x18\x01 \x01(\t\x12\x36\n\x08selector\x18\x02 \x03(\x0b\x32$.mlrun.StartLogRequest.SelectorEntry\x1a/\n\rSelectorEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"2\n\x10StartLogResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\r\n\x05\x65rror\x18\x02 \x01(\t2M\n\x0cLogCollector\x12=\n\x08StartLog\x12\x16.mlrun.StartLogRequest\x1a\x17.mlrun.StartLogResponse\"\x00\x42\x1bZ\x19proto/build/log_collectorb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_STARTLOGREQUEST_SELECTORENTRY = _descriptor.Descriptor(
  name='SelectorEntry',
  full_name='mlrun.StartLogRequest.SelectorEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='mlrun.StartLogRequest.SelectorEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='mlrun.StartLogRequest.SelectorEntry.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=203,
)

_STARTLOGREQUEST = _descriptor.Descriptor(
  name='StartLogRequest',
  full_name='mlrun.StartLogRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='runId', full_name='mlrun.StartLogRequest.runId', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='selector', full_name='mlrun.StartLogRequest.selector', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_STARTLOGREQUEST_SELECTORENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=203,
)


_STARTLOGRESPONSE = _descriptor.Descriptor(
  name='StartLogResponse',
  full_name='mlrun.StartLogResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='mlrun.StartLogResponse.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='error', full_name='mlrun.StartLogResponse.error', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=255,
)

_STARTLOGREQUEST_SELECTORENTRY.containing_type = _STARTLOGREQUEST
_STARTLOGREQUEST.fields_by_name['selector'].message_type = _STARTLOGREQUEST_SELECTORENTRY
DESCRIPTOR.message_types_by_name['StartLogRequest'] = _STARTLOGREQUEST
DESCRIPTOR.message_types_by_name['StartLogResponse'] = _STARTLOGRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

StartLogRequest = _reflection.GeneratedProtocolMessageType('StartLogRequest', (_message.Message,), {

  'SelectorEntry' : _reflection.GeneratedProtocolMessageType('SelectorEntry', (_message.Message,), {
    'DESCRIPTOR' : _STARTLOGREQUEST_SELECTORENTRY,
    '__module__' : 'proto.log_collector_pb2'
    # @@protoc_insertion_point(class_scope:mlrun.StartLogRequest.SelectorEntry)
    })
  ,
  'DESCRIPTOR' : _STARTLOGREQUEST,
  '__module__' : 'proto.log_collector_pb2'
  # @@protoc_insertion_point(class_scope:mlrun.StartLogRequest)
  })
_sym_db.RegisterMessage(StartLogRequest)
_sym_db.RegisterMessage(StartLogRequest.SelectorEntry)

StartLogResponse = _reflection.GeneratedProtocolMessageType('StartLogResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTLOGRESPONSE,
  '__module__' : 'proto.log_collector_pb2'
  # @@protoc_insertion_point(class_scope:mlrun.StartLogResponse)
  })
_sym_db.RegisterMessage(StartLogResponse)


DESCRIPTOR._options = None
_STARTLOGREQUEST_SELECTORENTRY._options = None

_LOGCOLLECTOR = _descriptor.ServiceDescriptor(
  name='LogCollector',
  full_name='mlrun.LogCollector',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=257,
  serialized_end=334,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartLog',
    full_name='mlrun.LogCollector.StartLog',
    index=0,
    containing_service=None,
    input_type=_STARTLOGREQUEST,
    output_type=_STARTLOGRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LOGCOLLECTOR)

DESCRIPTOR.services_by_name['LogCollector'] = _LOGCOLLECTOR

# @@protoc_insertion_point(module_scope)
