# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""add function kind

Revision ID: 0914542d88f0
Revises: 2fa14ac323db
Create Date: 2024-11-14 11:01:14.913111

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0914542d88f0"
down_revision = "12d8000e609b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "functions",
        sa.Column(
            "kind", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("functions", "kind")
    # ### end Alembic commands ###
