# Copyright 2026 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""squash_before_v1_7

Revision ID: 0cae47e3a844
Revises:
Create Date: 2026-04-16 13:09:29.950800

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "0cae47e3a844"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "artifacts",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("body", mysql.MEDIUMBLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_uc", "artifacts", ["uid", "project", "key"], unique=True
    )
    op.create_table(
        "artifacts_v2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("key", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column(
            "kind", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "producer_id", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("iteration", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("best_iteration", sa.Boolean(), nullable=True),
        sa.Column("object", mysql.MEDIUMBLOB(), nullable=True),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_v2_uc", "artifacts_v2", ["uid", "project", "key"], unique=True
    )
    op.create_index(
        "idx_artifacts_producer_id_best_iteration_and_project",
        "artifacts_v2",
        ["project", "producer_id", "best_iteration"],
        unique=False,
    )
    op.create_index(
        "ix_artifacts_v2_best_iteration",
        "artifacts_v2",
        ["best_iteration"],
        unique=False,
    )
    op.create_index("ix_artifacts_v2_key", "artifacts_v2", ["key"], unique=False)
    op.create_index("ix_artifacts_v2_kind", "artifacts_v2", ["kind"], unique=False)
    op.create_table(
        "background_tasks",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("timeout", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "error", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_background_tasks_uc", "background_tasks", ["name", "project"], unique=True
    )
    op.create_table(
        "data_versions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "version", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_versions_uc", "data_versions", ["version"], unique=True)
    op.create_table(
        "datastore_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "type", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_datastore_profiles_uc", "datastore_profiles", ["name", "project"], unique=True
    )
    op.create_table(
        "feature_sets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_set_uc", "feature_sets", ["name", "project", "uid"], unique=True
    )
    op.create_table(
        "feature_vectors",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_vectors_uc",
        "feature_vectors",
        ["name", "project", "uid"],
        unique=True,
    )
    op.create_table(
        "functions",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column("body", mysql.MEDIUMBLOB(), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_functions_uc", "functions", ["name", "project", "uid"], unique=True
    )
    op.create_table(
        "hub_sources",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("index", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("object", sa.JSON(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_marketplace_sources_uc", "hub_sources", ["name"], unique=True)
    op.create_table(
        "logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("body", mysql.MEDIUMBLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "description", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "owner", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "source", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("spec", mysql.MEDIUMBLOB(), nullable=True),
        sa.Column("created", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_projects_uc", "projects", ["name"], unique=True)
    op.create_table(
        "runs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("uid", sa.String(length=255, collation="utf8mb3_bin"), nullable=True),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("iteration", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("body", mysql.MEDIUMBLOB(), nullable=True),
        sa.Column("start_time", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("updated", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column("requested_logs", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_runs_uc", "runs", ["uid", "project", "iteration"], unique=True)
    op.create_index("idx_runs_project_id", "runs", ["id", "project"], unique=True)
    op.create_index("ix_runs_requested_logs", "runs", ["requested_logs"], unique=False)
    op.create_table(
        "schedules_v2",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "kind", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "desired_state",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=True,
        ),
        sa.Column(
            "state", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("creation_time", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "cron_trigger_str",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=True,
        ),
        sa.Column(
            "last_run_uri",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=True,
        ),
        sa.Column("struct", mysql.MEDIUMBLOB(), nullable=True),
        sa.Column(
            "concurrency_limit", sa.Integer(), autoincrement=False, nullable=False
        ),
        sa.Column("next_run_time", mysql.DATETIME(fsp=3), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_schedules_v2_uc", "schedules_v2", ["project", "name"], unique=True
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_users_uc", "users", ["name"], unique=True)
    op.create_table(
        "artifacts_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["artifacts.id"], name="_artifacts_labels_paren_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_labels_paren_fk", "artifacts_labels", ["parent"], unique=False
    )
    op.create_index(
        "_artifacts_labels_uc", "artifacts_labels", ["name", "parent"], unique=True
    )
    op.create_index(
        "idx_artifacts_labels_name_value",
        "artifacts_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "artifacts_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["obj_id"], ["artifacts.id"], name="_artifacts_tags_obj_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_tags_obj_id_fk", "artifacts_tags", ["obj_id"], unique=False
    )
    op.create_index(
        "_artifacts_tags_uc",
        "artifacts_tags",
        ["project", "name", "obj_id"],
        unique=True,
    )
    op.create_table(
        "artifacts_v2_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["artifacts_v2.id"], name="artifacts_v2_labels_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_v2_labels_uc",
        "artifacts_v2_labels",
        ["name", "parent"],
        unique=True,
    )
    op.create_index("parent", "artifacts_v2_labels", ["parent"], unique=False)
    op.create_table(
        "artifacts_v2_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "obj_name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["obj_id"], ["artifacts_v2.id"], name="artifacts_v2_tags_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_artifacts_v2_tags_uc",
        "artifacts_v2_tags",
        ["project", "name", "obj_id"],
        unique=True,
    )
    op.create_index(
        "idx_artifacts_v2_tags_project_name_obj_name",
        "artifacts_v2_tags",
        ["project", "name", "obj_name"],
        unique=False,
    )
    op.create_index("obj_id", "artifacts_v2_tags", ["obj_id"], unique=False)
    op.create_table(
        "entities",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feature_set_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value_type", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_id"], ["feature_sets.id"], name="_entities_feature_set_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_entities_feature_set_id_fk", "entities", ["feature_set_id"], unique=False
    )
    op.create_table(
        "feature_sets_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["feature_sets.id"], name="_feature_sets_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_sets_labels_parent_fk",
        "feature_sets_labels",
        ["parent"],
        unique=False,
    )
    op.create_index(
        "_feature_sets_labels_uc",
        "feature_sets_labels",
        ["name", "parent"],
        unique=True,
    )
    op.create_index(
        "idx_feature_sets_labels_name_value",
        "feature_sets_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "feature_sets_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "obj_name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["obj_id"], ["feature_sets.id"], name="_feature_sets_tags_obj_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_sets_tags_obj_id_fk", "feature_sets_tags", ["obj_id"], unique=False
    )
    op.create_index(
        "_feature_sets_tags_obj_name_fk",
        "feature_sets_tags",
        ["obj_name"],
        unique=False,
    )
    op.create_index(
        "_feature_sets_tags_uc",
        "feature_sets_tags",
        ["project", "name", "obj_name"],
        unique=True,
    )
    op.create_table(
        "feature_vectors_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["feature_vectors.id"], name="_feature_vectors_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_vectors_labels_parent_fk",
        "feature_vectors_labels",
        ["parent"],
        unique=False,
    )
    op.create_index(
        "_feature_vectors_labels_uc",
        "feature_vectors_labels",
        ["name", "parent"],
        unique=True,
    )
    op.create_index(
        "idx_feature_vectors_labels_name_value",
        "feature_vectors_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "feature_vectors_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "obj_name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["obj_id"], ["feature_vectors.id"], name="_feature_vectors_tags_obj_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_feature_vectors_tags_obj_id_fk",
        "feature_vectors_tags",
        ["obj_id"],
        unique=False,
    )
    op.create_index(
        "_feature_vectors_tags_obj_name_fk",
        "feature_vectors_tags",
        ["obj_name"],
        unique=False,
    )
    op.create_index(
        "_feature_vectors_tags_uc",
        "feature_vectors_tags",
        ["project", "name", "obj_name"],
        unique=True,
    )
    op.create_table(
        "features",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("feature_set_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value_type", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["feature_set_id"], ["feature_sets.id"], name="_features_feature_set_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_features_feature_set_id_fk", "features", ["feature_set_id"], unique=False
    )
    op.create_table(
        "functions_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["functions.id"], name="_functions_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_functions_labels_parent_fk", "functions_labels", ["parent"], unique=False
    )
    op.create_index(
        "_functions_labels_uc", "functions_labels", ["name", "parent"], unique=True
    )
    op.create_index(
        "idx_functions_labels_name_value",
        "functions_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "functions_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column(
            "obj_name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["obj_id"], ["functions.id"], name="_functions_tags_obj_id_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_functions_tags_obj_id_fk", "functions_tags", ["obj_id"], unique=False
    )
    op.create_index(
        "_functions_tags_obj_name_fk", "functions_tags", ["obj_name"], unique=False
    )
    op.create_index(
        "_functions_tags_uc",
        "functions_tags",
        ["project", "name", "obj_name"],
        unique=True,
    )
    op.create_table(
        "project_users",
        sa.Column("project_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("user_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["project_id"], ["projects.id"], name="_project_users_project_id_fk"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name="_project_users_user_id_fk"
        ),
    )
    op.create_index(
        "_project_users_project_id_fk", "project_users", ["project_id"], unique=False
    )
    op.create_index(
        "_project_users_user_id_fk", "project_users", ["user_id"], unique=False
    )
    op.create_table(
        "projects_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["projects.id"], name="_projects_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_projects_labels_parent_fk", "projects_labels", ["parent"], unique=False
    )
    op.create_index(
        "_projects_labels_uc", "projects_labels", ["name", "parent"], unique=True
    )
    op.create_index(
        "idx_projects_labels_name_value",
        "projects_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "runs_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["parent"], ["runs.id"], name="_runs_labels_parent_fk"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_runs_labels_parent_fk", "runs_labels", ["parent"], unique=False)
    op.create_index("_runs_labels_uc", "runs_labels", ["name", "parent"], unique=True)
    op.create_index(
        "idx_runs_labels_name_value", "runs_labels", ["name", "value"], unique=False
    )
    op.create_table(
        "runs_notifications",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "kind", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "message", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "severity", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "when", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "condition", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("secret_params", sa.JSON(), nullable=True),
        sa.Column("parent_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.Column("sent_time", mysql.DATETIME(fsp=3), nullable=True),
        sa.Column(
            "status", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column("params", sa.JSON(), nullable=True),
        sa.Column(
            "reason", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.ForeignKeyConstraint(
            ["parent_id"], ["runs.id"], name="runs_notifications_ibfk_1"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_runs_notifications_uc",
        "runs_notifications",
        ["name", "parent_id"],
        unique=True,
    )
    op.create_index("parent_id", "runs_notifications", ["parent_id"], unique=False)
    op.create_table(
        "runs_tags",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("obj_id", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(["obj_id"], ["runs.id"], name="_runs_tags_obj_id_fk"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("_runs_tags_obj_id_fk", "runs_tags", ["obj_id"], unique=False)
    op.create_index(
        "_runs_tags_uc", "runs_tags", ["project", "name", "obj_id"], unique=True
    )
    op.create_table(
        "schedules_v2_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["schedules_v2.id"], name="_schedules_v2_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_schedules_v2_labels_parent_fk",
        "schedules_v2_labels",
        ["parent"],
        unique=False,
    )
    op.create_index(
        "_schedules_v2_labels_uc",
        "schedules_v2_labels",
        ["name", "parent"],
        unique=True,
    )
    op.create_index(
        "idx_schedules_v2_labels_name_value",
        "schedules_v2_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "entities_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["entities.id"], name="_entities_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_entities_labels_parent_fk", "entities_labels", ["parent"], unique=False
    )
    op.create_index(
        "_entities_labels_uc", "entities_labels", ["name", "parent"], unique=True
    )
    op.create_index(
        "idx_entities_labels_name_value",
        "entities_labels",
        ["name", "value"],
        unique=False,
    )
    op.create_table(
        "features_labels",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "name", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column(
            "value", sa.String(length=255, collation="utf8mb3_bin"), nullable=True
        ),
        sa.Column("parent", sa.Integer(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["parent"], ["features.id"], name="_features_labels_parent_fk"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "_features_labels_parent_fk", "features_labels", ["parent"], unique=False
    )
    op.create_index(
        "_features_labels_uc", "features_labels", ["name", "parent"], unique=True
    )
    op.create_index(
        "idx_features_labels_name_value",
        "features_labels",
        ["name", "value"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("features_labels")
    op.drop_table("entities_labels")
    op.drop_table("schedules_v2_labels")
    op.drop_table("runs_tags")
    op.drop_table("runs_notifications")
    op.drop_table("runs_labels")
    op.drop_table("projects_labels")
    op.drop_table("project_users")
    op.drop_table("functions_tags")
    op.drop_table("functions_labels")
    op.drop_table("features")
    op.drop_table("feature_vectors_tags")
    op.drop_table("feature_vectors_labels")
    op.drop_table("feature_sets_tags")
    op.drop_table("feature_sets_labels")
    op.drop_table("entities")
    op.drop_table("artifacts_v2_tags")
    op.drop_table("artifacts_v2_labels")
    op.drop_table("artifacts_tags")
    op.drop_table("artifacts_labels")
    op.drop_table("users")
    op.drop_table("schedules_v2")
    op.drop_table("runs")
    op.drop_table("projects")
    op.drop_table("logs")
    op.drop_table("hub_sources")
    op.drop_table("functions")
    op.drop_table("feature_vectors")
    op.drop_table("feature_sets")
    op.drop_table("datastore_profiles")
    op.drop_table("data_versions")
    op.drop_table("background_tasks")
    op.drop_table("artifacts_v2")
    op.drop_table("artifacts")
    # ### end Alembic commands ###
