"""test

Revision ID: 12d8000e609b
Revises: d579650595c3
Create Date: 2024-11-13 13:45:08.512249

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "12d8000e609b"
down_revision = "2fa14ac323db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_alert_activation_uc", "alert_activation", type_="primary")
    op.create_primary_key(
        "_alert_activation_uc", "alert_activation", ["id", "activation_time"]
    )

    op.execute("""
        ALTER TABLE alert_activation
        MODIFY COLUMN id INT NOT NULL AUTO_INCREMENT
    """)

    # ### end Alembic commands ###


def downgrade():
    op.execute("""
                ALTER TABLE alert_activation
                MODIFY COLUMN id INT NOT NULL
            """)

    op.drop_constraint("_alert_activation_uc", "alert_activation", type_="primary")
    op.create_primary_key(
        "_alert_activation_uc", "alert_activation", ["activation_time", "id"]
    )
    # ### end Alembic commands ###
