# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
"""add autoincrement to alert activation

Revision ID: 21b8e805f7ab
Revises: 2fa14ac323db
Create Date: 2024-11-13 13:48:28.927628

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "21b8e805f7ab"
down_revision = "2fa14ac323db"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "alert_activation", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "alert_activation", type_="unique")
    # ### end Alembic commands ###
