# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""datetime fsp to 6

Revision ID: 22dd9f3bdc66
Revises: 6f9a8e3857ec
Create Date: 2025-03-02 17:54:28.738705

"""

from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "22dd9f3bdc66"
down_revision = "6f9a8e3857ec"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "project_summaries",
        "updated",
        existing_type=mysql.DATETIME(fsp=3),
        type_=mysql.DATETIME(timezone=True, fsp=6),
        existing_nullable=True,
    )
    op.alter_column(
        "runs",
        "end_time",
        existing_type=mysql.DATETIME(fsp=3),
        type_=mysql.DATETIME(timezone=True, fsp=6),
        existing_nullable=True,
    )
    op.alter_column(
        "time_window_trackers",
        "timestamp",
        existing_type=mysql.DATETIME(fsp=3),
        type_=mysql.DATETIME(timezone=True, fsp=6),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "time_window_trackers",
        "timestamp",
        existing_type=mysql.DATETIME(timezone=True, fsp=6),
        type_=mysql.DATETIME(fsp=3),
        existing_nullable=False,
    )
    op.alter_column(
        "runs",
        "end_time",
        existing_type=mysql.DATETIME(timezone=True, fsp=6),
        type_=mysql.DATETIME(fsp=3),
        existing_nullable=True,
    )
    op.alter_column(
        "project_summaries",
        "updated",
        existing_type=mysql.DATETIME(timezone=True, fsp=6),
        type_=mysql.DATETIME(fsp=3),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
