# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""artifact project_bi_updated index

Revision ID: 2abdb7a8f1e6
Revises: 2a37ea63671d
Create Date: 2025-02-04 11:57:06.040713

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "2abdb7a8f1e6"
down_revision = "2a37ea63671d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_bi_updated",
        "artifacts_v2",
        ["project", "best_iteration", "updated"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_project_bi_updated", table_name="artifacts_v2")
    # ### end Alembic commands ###
