"""add function kind

Revision ID: 488e5710bd35
Revises: 2fa14ac323db
Create Date: 2024-11-14 10:00:26.405932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '488e5710bd35'
down_revision = '2fa14ac323db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('functions', sa.Column('kind', sa.String(length=255, collation='utf8mb3_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('functions', 'kind')
    # ### end Alembic commands ###
