# Copyright 2026 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""add project sync fields

Revision ID: 4a4172268db0
Revises: 24a254635f94
Create Date: 2026-04-28 14:53:05.477105

"""

import sqlalchemy as sa
from alembic import op

import framework.db.sqldb.sql_types

# revision identifiers, used by Alembic.
revision = "4a4172268db0"
down_revision = "8712e85b0281"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("op_id", framework.db.sqldb.sql_types.UuidType(), nullable=True),
    )
    op.add_column("projects", sa.Column("phase", sa.Integer(), nullable=True))
    op.add_column(
        "projects",
        sa.Column("updated_at", framework.db.sqldb.sql_types.DateTime(), nullable=True),
    )
    op.create_index(
        op.f("ix_projects_updated_at"), "projects", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_projects_updated_at"), table_name="projects")
    op.drop_column("projects", "updated_at")
    op.drop_column("projects", "phase")
    op.drop_column("projects", "op_id")
    # ### end Alembic commands ###
