# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Add model_db_key to model_endpoints

Revision ID: 537d9a20c4b4
Revises: 9825ab4aa036
Create Date: 2024-12-12 14:22:13.079282

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "537d9a20c4b4"
down_revision = "9825ab4aa036"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_endpoints",
        sa.Column(
            "model_tag", sa.String(length=64, collation="utf8mb3_bin"), nullable=True
        ),
    )
    op.add_column(
        "model_endpoints",
        sa.Column(
            "model_db_key",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("model_endpoints", "model_db_key")
    op.drop_column("model_endpoints", "model_tag")
    # ### end Alembic commands ###
