# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""artifact project_kind_key index

Revision ID: 63a7eec6d034
Revises: dd6049a25a81
Create Date: 2024-12-26 10:22:25.697652

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "63a7eec6d034"
down_revision = "dd6049a25a81"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_kind_key", "artifacts_v2", ["project", "kind", "key"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_project_kind_key", table_name="artifacts_v2")
    # ### end Alembic commands ###
