# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""idx_project_state

Revision ID: 692f2f936258
Revises: 528d9f5ea91d
Create Date: 2025-06-17 16:35:25.754423

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "692f2f936258"
down_revision = "528d9f5ea91d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_project_state", "functions", ["project", "state"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_project_state", table_name="functions")
    # ### end Alembic commands ###
