# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""modify background task label uc

Revision ID: 6d1d53f60e90
Revises: 0da0066c77f5
Create Date: 2025-11-18 09:44:39.663052

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d1d53f60e90"
down_revision = "0da0066c77f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "background_task_labels",
        sa.Column("project", sa.String(255, collation="utf8mb3_bin"), nullable=False),
    )
    op.drop_index(
        "uq_bg_task_labels_task_id_and_name", table_name="background_task_labels"
    )
    op.create_unique_constraint(
        "uq_bg_task_labels_project_name_value",
        "background_task_labels",
        ["project", "name", "value"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_bg_task_labels_project_name_value", "background_task_labels", type_="unique"
    )
    op.create_index(
        "uq_bg_task_labels_task_id_and_name",
        "background_task_labels",
        ["task_id", "name"],
        unique=True,
    )
    op.drop_column("background_task_labels", "project")
    # ### end Alembic commands ###
