# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""modify background task label uc

Revision ID: 6d1d53f60e90
Revises: 0da0066c77f5
Create Date: 2025-11-18 09:44:39.663052

This migration changes the unique constraint on background_task_labels from (task_id, name) to
(project, name, value) and adds a new `project` column.

The original version of this migration added `project` as NOT NULL and applied the new constraint directly,
which failed on upgrades from < 1.11.0 when the table already contained data.
Two issues caused the failure:

1. Under the old (task_id, name) constraint, near-simultaneous requests could create labels with the same
   (name, value) under different task_ids in the same project.
   After backfilling `project` from the parent table, these rows become duplicates under the new (project, name, value)
   constraint, causing an IntegrityError.

2. The column was added as NOT NULL without backfilling, so existing rows with NULL project would be rejected.

The fix:
  1. Add `project` as nullable
  2. Backfill from the parent background_tasks table
  3. Deduplicate (project, name, value) rows, keeping the latest entry
  4. Alter the column to NOT NULL
  5. Drop the old constraint and create the new one

See: ML-11774 for more details.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d1d53f60e90"
down_revision = "0da0066c77f5"
branch_labels = None
depends_on = None


def _backfill_project_from_parent(connection):
    """Populate the project column from the parent background_tasks table."""
    connection.execute(
        sa.text(
            """
            UPDATE background_task_labels btl
            JOIN background_tasks bt ON bt.id = btl.task_id
            SET btl.project = bt.project
            """
        )
    )


def _remove_duplicates(connection):
    """Remove duplicate (project, name, value) rows, keeping the latest entry.

    After backfilling the project column, there may be rows that share the same (project, name, value) tuple
    for example, two labels created by near-simultaneous requests under the old (task_id, name) constraint.
    We keep only one row per group so the new unique constraint can be applied.
    """
    connection.execute(
        sa.text(
            """
            DELETE FROM background_task_labels
            WHERE id NOT IN (
                SELECT keep_id FROM (
                    SELECT MAX(id) AS keep_id
                    FROM background_task_labels
                    GROUP BY project, name, value
                ) AS keep_rows
            )
            """
        )
    )


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Add the project column as nullable so existing rows are not rejected
    op.add_column(
        "background_task_labels",
        sa.Column("project", sa.String(255, collation="utf8mb3_bin"), nullable=True),
    )

    # Backfill project from the parent background_tasks table
    _backfill_project_from_parent(connection)

    # Remove duplicate (project, name, value) rows before applying the new unique constraint
    _remove_duplicates(connection)

    # Now make the column NOT NULL
    op.alter_column(
        "background_task_labels",
        "project",
        existing_type=sa.String(255, collation="utf8mb3_bin"),
        nullable=False,
    )

    # Drop old unique constraint and create the new one
    op.drop_index(
        "uq_bg_task_labels_task_id_and_name", table_name="background_task_labels"
    )
    op.create_unique_constraint(
        "uq_bg_task_labels_project_name_value",
        "background_task_labels",
        ["project", "name", "value"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_bg_task_labels_project_name_value", "background_task_labels", type_="unique"
    )
    op.create_index(
        "uq_bg_task_labels_task_id_and_name",
        "background_task_labels",
        ["task_id", "name"],
        unique=True,
    )
    op.drop_column("background_task_labels", "project")
    # ### end Alembic commands ###
