# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""modify background task label uc

Revision ID: 6d1d53f60e90
Revises: 0da0066c77f5
Create Date: 2025-11-18 09:44:39.663052

Existing rows need backfilling (project is derived from the parent background_tasks table)
and deduplication (the old constraint allowed rows that become duplicates under the new one).

See ML-11774 for full context.
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6d1d53f60e90"
down_revision = "0da0066c77f5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    connection = op.get_bind()

    # Add the project column as nullable so existing rows are not rejected
    op.add_column(
        "background_task_labels",
        sa.Column("project", sa.String(255, collation="utf8mb3_bin"), nullable=True),
    )

    # Backfill project from the parent background_tasks table
    _backfill_project_from_parent(connection)

    # Remove duplicate (project, name, value) rows before applying the new unique constraint
    _remove_duplicates(connection)

    # Now make the column NOT NULL
    op.alter_column(
        "background_task_labels",
        "project",
        existing_type=sa.String(255, collation="utf8mb3_bin"),
        nullable=False,
    )

    # Drop old unique constraint and create the new one
    op.drop_index(
        "uq_bg_task_labels_task_id_and_name", table_name="background_task_labels"
    )
    op.create_unique_constraint(
        "uq_bg_task_labels_project_name_value",
        "background_task_labels",
        ["project", "name", "value"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_bg_task_labels_project_name_value", "background_task_labels", type_="unique"
    )
    op.create_index(
        "uq_bg_task_labels_task_id_and_name",
        "background_task_labels",
        ["task_id", "name"],
        unique=True,
    )
    op.drop_column("background_task_labels", "project")
    # ### end Alembic commands ###


def _backfill_project_from_parent(connection):
    """Populate the project column from the parent background_tasks table."""
    if connection.dialect.name == "mysql":
        connection.execute(
            sa.text(
                """
                UPDATE background_task_labels btl
                JOIN background_tasks bt ON bt.id = btl.task_id
                SET btl.project = bt.project
                """
            )
        )
    else:
        connection.execute(
            sa.text(
                """
                UPDATE background_task_labels
                SET project = bt.project
                FROM background_tasks bt
                WHERE bt.id = background_task_labels.task_id
                """
            )
        )


def _remove_duplicates(connection):
    """Remove duplicate (project, name, value) rows, keeping the latest entry.

    After backfilling the project column, there may be rows that share the same (project, name, value) tuple
    for example, two labels created by near-simultaneous requests under the old (task_id, name) constraint.
    We keep only one row per group so the new unique constraint can be applied.
    """
    if connection.dialect.name == "mysql":
        connection.execute(
            sa.text(
                """
                DELETE btl FROM background_task_labels btl
                INNER JOIN (
                    SELECT project, name, value, MAX(id) AS keep_id
                    FROM background_task_labels
                    GROUP BY project, name, value
                ) keep ON btl.project = keep.project
                    AND btl.name = keep.name
                    AND btl.value = keep.value
                    AND btl.id != keep.keep_id
                """
            )
        )
    else:
        connection.execute(
            sa.text(
                """
                DELETE FROM background_task_labels btl
                USING (
                    SELECT project, name, value, MAX(id) AS keep_id
                    FROM background_task_labels
                    GROUP BY project, name, value
                ) keep
                WHERE btl.project = keep.project
                    AND btl.name = keep.name
                    AND btl.value = keep.value
                    AND btl.id != keep.keep_id
                """
            )
        )
