"""adding column producer_uri to table ArtifactV2

Revision ID: 775b4269f779
Revises: 12d8000e609b
Create Date: 2024-11-14 14:38:41.732698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '775b4269f779'
down_revision = '12d8000e609b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artifacts_v2', sa.Column('producer_uri', sa.String(length=255, collation='utf8mb3_bin'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artifacts_v2', 'producer_uri')
    # ### end Alembic commands ###
