# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""squash v1.12 migrations

Revision ID: 7bbf7ca69cb8
Revises: 4a4172268db0
Create Date: 2026-06-17 11:43:54.018360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bbf7ca69cb8'
down_revision = '4a4172268db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_function_project_kind', 'functions', ['project', 'kind'], unique=False)
    op.drop_index(op.f('idx_runs_project_iter_start'), table_name='runs')
    op.create_index('idx_runs_project_iter_start_updated', 'runs', ['project', 'iteration', 'start_time', 'name', 'updated'], unique=False)
    op.create_index('idx_runs_project_iter_state_start_updated', 'runs', ['project', 'iteration', 'state', 'start_time', 'name', 'updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_runs_project_iter_state_start_updated', table_name='runs')
    op.drop_index('idx_runs_project_iter_start_updated', table_name='runs')
    op.create_index(op.f('idx_runs_project_iter_start'), 'runs', ['project', 'iteration', 'start_time', 'name'], unique=False)
    op.drop_index('idx_function_project_kind', table_name='functions')
    # ### end Alembic commands ###
