# Copyright 2026 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Index runs project iteration start_time

Revision ID: 8712e85b0281
Revises: 24a254635f94
Create Date: 2026-04-15 12:00:00.000000

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "8712e85b0281"
down_revision = "24a254635f94"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_runs_project_iter_start",
        "runs",
        ["project", "iteration", "start_time"],
        unique=False,
        if_not_exists=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_runs_project_iter_start", table_name="runs")
    # ### end Alembic commands ###
