# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""add system metadata table

Revision ID: 979e3ad220d7
Revises: 1e57ec862f09
Create Date: 2024-12-17 09:55:50.249502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '979e3ad220d7'
down_revision = '1e57ec862f09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_metadata', 'key',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('system_metadata', 'key',
               existing_type=mysql.VARCHAR(charset='utf8mb3', collation='utf8mb3_bin', length=255),
               nullable=True)
    # ### end Alembic commands ###
