# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Add function tag to model_endpoints

Revision ID: 9825ab4aa036
Revises: d259d95707b3
Create Date: 2024-12-10 12:15:10.664348

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9825ab4aa036"
down_revision = "d259d95707b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_endpoints",
        sa.Column(
            "function_tag", sa.String(length=64, collation="utf8mb3_bin"), nullable=True
        ),
    )
    op.drop_constraint("_mep_uc_2", "model_endpoints", type_="unique")
    op.create_unique_constraint(
        "_mep_uc_2",
        "model_endpoints",
        ["project", "name", "uid", "function_name", "function_tag"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("_mep_uc_2", "model_endpoints", type_="unique")
    op.create_unique_constraint(
        "_mep_uc_2", "model_endpoints", ["project", "name", "uid", "function_name"]
    )
    op.drop_column("model_endpoints", "function_tag")
    # ### end Alembic commands ###
