# Copyright 2026 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Index functions project and kind

Revision ID: 9cae5c29c395
Revises: 4a4172268db0
Create Date: 2026-05-27 16:22:48.331376

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "9cae5c29c395"
down_revision = "4a4172268db0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_function_project_kind", "functions", ["project", "kind"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_function_project_kind", table_name="functions")
    # ### end Alembic commands ###
