# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""remove obsolete log table

Revision ID: aaa213106ec5
Revises: c53a7f5bcd3a
Create Date: 2024-12-06 10:27:50.669582

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "aaa213106ec5"
down_revision = "c53a7f5bcd3a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("logs")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "logs",
        sa.Column("id", mysql.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "uid",
            mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
            nullable=True,
        ),
        sa.Column(
            "project",
            mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
            nullable=True,
        ),
        sa.Column("body", mysql.MEDIUMBLOB(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        mysql_collate="utf8mb3_bin",
        mysql_default_charset="utf8mb3",
        mysql_engine="InnoDB",
    )
    # ### end Alembic commands ###
