# Copyright 2025 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Add partition key column for alerts activations partitioning in postgres

Revision ID: c25e56faecce
Revises: a6f358254cbd
Create Date: 2025-07-22 00:32:52.344545

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "c25e56faecce"
down_revision = "a6f358254cbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "alert_activations", sa.Column("partition_key", sa.Integer(), nullable=False)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("alert_activations", "partition_key")
    # ### end Alembic commands ###
