# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Update model_endpoints table

Revision ID: c53a7f5bcd3a
Revises: b103e4740e88
Create Date: 2024-12-01 12:50:52.893228

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "c53a7f5bcd3a"
down_revision = "b103e4740e88"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "model_endpoints",
        "uid",
        existing_type=mysql.VARCHAR(
            charset="utf8mb3", collation="utf8mb3_bin", length=255
        ),
        type_=sa.String(length=32),
        existing_nullable=True,
    )
    op.drop_constraint("_mep_uc_2", "model_endpoints", type_="unique")
    op.create_unique_constraint(
        "_mep_uc_2", "model_endpoints", ["project", "name", "uid", "function_name"]
    )
    op.create_unique_constraint("uid", "model_endpoints", ["uid"])
    op.drop_constraint("_mep_model_constraint", "model_endpoints", type_="foreignkey")
    op.drop_constraint(
        "_mep_function_constraint", "model_endpoints", type_="foreignkey"
    )
    op.drop_index("_mep_function_constraint", table_name="model_endpoints")
    op.drop_index("_mep_model_constraint", table_name="model_endpoints")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        "_mep_function_constraint",
        "model_endpoints",
        "functions",
        ["function_name", "function_uid", "project"],
        ["name", "uid", "project"],
    )
    op.create_foreign_key(
        "_mep_model_constraint",
        "model_endpoints",
        "artifacts_v2",
        ["model_uid", "project", "model_name"],
        ["uid", "project", "key"],
    )
    op.drop_constraint("uid", "model_endpoints", type_="unique")
    op.drop_constraint("_mep_uc_2", "model_endpoints", type_="unique")
    op.create_unique_constraint(
        "_mep_uc_2", "model_endpoints", ["project", "name", "uid"]
    )
    op.alter_column(
        "model_endpoints",
        "uid",
        existing_type=sa.String(length=32),
        type_=mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
