# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""create object_counters table

Revision ID: dd30a55311a7
Revises: 57d26493fbff
Create Date: 2024-12-18 11:54:42.169584

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "dd30a55311a7"
down_revision = "57d26493fbff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "object_counters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "project", sa.String(length=255, collation="utf8mb3_bin"), nullable=False
        ),
        sa.Column(
            "object_kind",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=False,
        ),
        sa.Column(
            "object_subkind",
            sa.String(length=255, collation="utf8mb3_bin"),
            nullable=True,
        ),
        sa.Column("counter", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project", "object_kind", "object_subkind", name="_object_counters_uc"
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("object_counters")
    # ### end Alembic commands ###
