# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

"""Update model endpoints table 2.0

Revision ID: ec572ac26e3e
Revises: 2abdb7a8f1e6
Create Date: 2025-02-23 23:36:22.460725

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "ec572ac26e3e"
down_revision = "2abdb7a8f1e6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_endpoints", sa.Column("function_id", sa.Integer(), nullable=True)
    )
    op.create_foreign_key(
        "fk_model_endpoints_functions",
        "model_endpoints",
        "functions",
        ["function_id"],
        ["id"],
        onupdate="CASCADE",
    )
    op.drop_column("model_endpoints", "model_db_key")
    op.drop_column("model_endpoints", "function_uid")
    op.drop_column("model_endpoints", "model_uid")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "model_endpoints",
        sa.Column(
            "model_uid",
            mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "model_endpoints",
        sa.Column(
            "function_uid",
            mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
            nullable=True,
        ),
    )
    op.add_column(
        "model_endpoints",
        sa.Column(
            "model_db_key",
            mysql.VARCHAR(charset="utf8mb3", collation="utf8mb3_bin", length=255),
            nullable=True,
        ),
    )
    op.drop_constraint(
        "fk_model_endpoints_functions", "model_endpoints", type_="foreignkey"
    )
    op.drop_column("model_endpoints", "function_id")
    # ### end Alembic commands ###
