# Copyright 2024 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""Update parent artifact deletion

Revision ID: fe9f3c286ae6
Revises: a6f358254cbd
Create Date: 2025-07-13 20:46:59.314061

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fe9f3c286ae6"
down_revision = "a6f358254cbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("parent_id_key", "artifacts_v2", type_="foreignkey")
    op.create_foreign_key(
        "parent_id_key_constraint",
        "artifacts_v2",
        "artifacts_v2",
        ["parent_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("parent_id_key_constraint", "artifacts_v2", type_="foreignkey")
    op.create_foreign_key(
        "parent_id_key",
        "artifacts_v2",
        "artifacts_v2",
        ["parent_id"],
        ["id"],
        ondelete="SET NULL",
    )
    # ### end Alembic commands ###
