{
 "title": "Model Monitoring - Overview",
 "description": "This dashboard provides an overview of the existing model endpoints. Please note that the summary table reflects the current system status and is not influenced by the selected time range",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROJECT", "label": "Project", "query": "target_endpoint=list_projects" }
  ]
 },
 "panels": [
  {
   "title": "Endpoints",
   "type": "stat",
   "description": "Number of active model endpoints in the system. Note that this KPI reflects the current system status and is not influenced by the selected time range.",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "target_endpoint=list_endpoints;project=$PROJECT",
     "type": "table"
    }
   ]
  },
  {
   "title": "Predictions/s (5 Minute Average)",
   "type": "stat",
   "description": "Average number of predictions per 5-minute interval for each model endpoint. Important Notes:\n- This KPI is based on the sampled invocations. If the sampling percentage is less than 100, the actual value may be higher.\n- This value excludes `router` model endpoints and reflects the invocation count for non-router models only.",
   "gridPos": { "h": 3, "w": 5, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields= predictions_count_5m;filter=endpoint_type!='2';",
     "type": "table"
    }
   ]
  },
  {
   "title": "Average Latency (Last Hour)",
   "type": "stat",
   "description": "Average latency per 1-hour interval for each model endpoint. Important Notes:\n- This KPI is based on the sampled invocations. If the sampling percentage is less than 100, the actual value may be different.\n- This value excludes `router` model endpoints and reflects the average latency for non-router models only.",
   "gridPos": { "h": 3, "w": 5, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields= latency_avg_1h;filter=endpoint_type!='2';",
     "type": "table"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "stat",
   "description": "Total number of errors within the selected time range.",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/errors;\nfields=error_count;",
     "type": "table"
    }
   ]
  },
  {
   "title": "Models",
   "type": "table",
   "description": "A summary table of the current model endpoints, with the following fields:\n\n- **Name**: The model endpoint name.\n- **Endpoint ID**: The unique identifier for the model endpoint. Clicking this value will redirect you to the relevant `Details` dashboard.\n- **Function**: The name of the function.\n- **Model Class**: The model object class (e.g., `SKLearnModelServer`).\n- **Error Count**: The total number of errors.\n- **Sampling Percentage**: The sampling rate percentage. By default (100), all events are sampled.\n- **Drift Status**: The drift status indicator, currently based on the `general_drift` result from the histogram default application.\n\nNote that this table reflects the current system status and is not influenced by the selected time range.",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "target": "target_endpoint=list_endpoints;project=$PROJECT",
     "type": "table"
    }
   ]
  },
  {
   "title": "Predictions/s (5 Minute Average)",
   "type": "heatmap",
   "description": "Heatmap displaying the average number of predictions per 5-minute interval. This value excludes `router` model endpoints and reflects the invocation count for non-router models only",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 16 },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields=predictions_per_second;filter=endpoint_type!='2';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Average Latency (1 Hour)",
   "type": "heatmap",
   "description": "Heatmap displaying average latency per 1-hour interval. Important Notes:\n- This KPI is based on the sampled invocations. If the sampling percentage is less than 100, the actual value may be different.\n- This value excludes `router` model endpoints and reflects the average latency for non-router models only.",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 16 },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields= latency_avg_1h;filter=endpoint_type!='2';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors by time for each model endpoint.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/errors;\nfields=error_count;",
     "type": "timeserie"
    }
   ]
  }
 ]
}