{
 "title": "Model Monitoring - Performance",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "PROJECT", "label": "Project", "query": "target_endpoint=list_projects" },
   {
    "name": "MODELENDPOINT",
    "label": "Model Endpoint",
    "query": "target_endpoint=list_endpoints;project=$PROJECT"
   }
  ]
 },
 "panels": [
  {
   "title": "Predictions/s (5 minute average)",
   "type": "timeseries",
   "description": "Average number of predictions per second over 5-minute intervals, by time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields=predictions_per_second;\nfilter=endpoint_id=='$MODELENDPOINT';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Average latency over time. Note that this chart displays both 5-minute and 1-hour intervals.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields=latency_avg_5m,latency_avg_1h;\nfilter=endpoint_id=='$MODELENDPOINT';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Errors over time.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/errors;\nfields=error_count;filter=endpoint_id=='$MODELENDPOINT'",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Predictions Count",
   "type": "timeseries",
   "description": "Number of predictions over time. Note that this chart displays both 5-minute and 1-hour intervals.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfields=predictions_count_5m,predictions_count_1h;\nfilter=endpoint_id=='$MODELENDPOINT';",
     "type": "timeserie"
    }
   ]
  },
  {
   "title": "Custom Metrics",
   "type": "timeseries",
   "description": "Custom metrics defined in the user’s serving function will be displayed on this chart.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "target": "backend=tsdb; container=users; table=pipelines/$PROJECT/model-endpoints/events; filter=endpoint_id=='$MODELENDPOINT'  AND record_type=='custom_metrics';",
     "type": "timeserie"
    }
   ]
  }
 ]
}