apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: k3d-mlrun-cicd
servers: 1
agents: 0
ports:
  - port: 30000-30120:30000-30120
    nodeFilters:
      - server:0
volumes:
  - volume: ${PWD}:/data/volume
    nodeFilters:
      - server:*
      - agent:*
registries:
  create:
    name: myregistry-cicd
options:
#  k3s:
#    extraArgs:
#      - arg: --no-deploy=traefik,servicelb,metrics-server
#        nodeFilters:
#          - server:*
  kubeconfig:
    updateDefaultKubeconfig: true
    switchCurrentContext: true
