FROM jupyter/scipy-notebook
RUN pip install mlrun
RUN pip install dask==2.9.1 distributed==2.9.1 kubernetes==10.0.0 dask_kubernetes==0.10.0 kubernetes-asyncio==10.0.0 msgpack==0.6.2
copy ./README.md /home/jovyan/
copy ./examples /home/jovyan/examples/

ENV MLRUN_ARTIFACT_PATH=/home/jovyan/data
ENV JUPYTER_ENABLE_LAB=yes

CMD start-notebook.sh \
    --ip="0.0.0.0" \
    --port=8888 \
    --NotebookApp.token='' \
    --NotebookApp.password='' \
    --NotebookApp.default_url="/lab"
