FROM jupyter/scipy-notebook
RUN python -m pip install \
    croniter \
#    dask-xgboost \
#    dask[complete] \
#    distributed \
    flask \
    mlrun 
#    xgboost

USER jovyan
COPY ./README.md /home/jovyan/
COPY ./examples /home/jovyan/examples/
RUN git clone https://github.com/yjb-ds/demos.git /home/jovyan/demos
RUN git clone https://github.com/yjb-ds/functions.git /home/jovyan/functions
#RUN git clone https://github.com/yjb-ds/demo-xgb-project.git /home/jovyan/demo-xgb-project
#RUN git clone https://github.com/yjb-ds/demo-sklearn-project.git /home/jovyan/demo-sklearn-project

USER root

ENV MLRUN_DBPATH=http://localhost:8080
ENV MLRUN_ARTIFACT_PATH=/home/jovyan/data
ENV MLRUN_HTTPDB__DATA_VOLUME=/home/jovyan/data
ENV MLRUN_HTTPDB__DB_TYPE=filerundb
ENV MLRUN_HTTPDB__DIRPATH=/home/jovyan/data/.db

CMD mlrun db & start-notebook.sh \
    --ip="0.0.0.0" \
    --port=8888 \
    --NotebookApp.token='' \
    --NotebookApp.password='' \
    --NotebookApp.default_url="/lab"
