"""Adding version table

Revision ID: de91dab72e33
Revises: d781f58f607f
Create Date: 2021-09-28 01:11:35.686939

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "de91dab72e33"
down_revision = "d781f58f607f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "versions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("created", sa.TIMESTAMP(), nullable=True),
        sa.Column("updated", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="_versions_uc"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("versions")
    # ### end Alembic commands ###
