{
 "title": "Model Monitoring - Details",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "PROJECT", "label": "Project", "query": "target_endpoint=list_projects" },
   {
    "name": "MODEL",
    "label": "Model",
    "query": "backend=kv;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/endpoints;\nfields=endpoint_id;"
   }
  ]
 },
 "panels": [
  {
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "target": "backend=kv;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/endpoints;\nfilter=endpoint_id==\"$MODEL\";\nfields=endpoint_id,model,function_uri,model_class,predictions_per_second,latency_avg_1h,first_request,last_request;",
     "type": "table"
    }
   ]
  },
  {
   "title": "Overall Drift Analysis",
   "type": "table",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "target": "target_endpoint=overall_feature_analysis;endpoint_id=$MODEL;project=$PROJECT",
     "type": "table"
    }
   ]
  },
  {
   "title": "Features Analysis",
   "type": "table",
   "description": "Feature analysis of the latest batch",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "target": "target_endpoint=individual_feature_analysis;endpoint_id=$MODEL;project=$PROJECT",
     "type": "table"
    }
   ]
  },
  {
   "title": "Incoming Features",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "backend=tsdb;\ncontainer=users;\ntable=pipelines/$PROJECT/model-endpoints/events;\nfilter=endpoint_id=='$MODEL'  AND record_type=='endpoint_features';",
     "type": "timeserie"
    }
   ]
  }
 ]
}