"""indexing artifact_v2 key

Revision ID: 0b224a1b4e0d
Revises: fa3009d9787f
Create Date: 2024-02-07 14:47:10.021608

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "0b224a1b4e0d"
down_revision = "fa3009d9787f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_artifacts_v2_key"), "artifacts_v2", ["key"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_v2_key"), table_name="artifacts_v2")
    # ### end Alembic commands ###
