"""add index migration

Revision ID: bf91ff18513b
Revises: 27ed4ecb734c
Create Date: 2023-11-05 12:43:39.286669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf91ff18513b'
down_revision = '27ed4ecb734c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_runs_project_uid', 'runs', ['id', 'project'], unique=True)
    op.create_index('idx_artifacts_labels_name_value', 'artifacts_labels', ['name', 'value'], unique=False)
    op.create_index('idx_entities_labels_name_value', 'entities_labels', ['name', 'value'], unique=False)
    op.create_index('idx_feature_sets_labels_name_value', 'feature_sets_labels', ['name', 'value'], unique=False)
    op.create_index('idx_feature_vectors_labels_name_value', 'feature_vectors_labels', ['name', 'value'], unique=False)
    op.create_index('idx_features_labels_name_value', 'features_labels', ['name', 'value'], unique=False)
    op.create_index('idx_functions_labels_name_value', 'functions_labels', ['name', 'value'], unique=False)
    op.create_index('idx_projects_labels_name_value', 'projects_labels', ['name', 'value'], unique=False)
    op.create_index('idx_runs_labels_name_value', 'runs_labels', ['name', 'value'], unique=False)
    op.create_index('idx_schedules_v2_labels_name_value', 'schedules_v2_labels', ['name', 'value'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_schedules_v2_labels_name_value', table_name='schedules_v2_labels')
    op.drop_index('idx_runs_labels_name_value', table_name='runs_labels')
    op.drop_index('idx_runs_project_uid', table_name='runs')
    op.drop_index('idx_projects_labels_name_value', table_name='projects_labels')
    op.drop_index('idx_functions_labels_name_value', table_name='functions_labels')
    op.drop_index('idx_features_labels_name_value', table_name='features_labels')
    op.drop_index('idx_feature_vectors_labels_name_value', table_name='feature_vectors_labels')
    op.drop_index('idx_feature_sets_labels_name_value', table_name='feature_sets_labels')
    op.drop_index('idx_entities_labels_name_value', table_name='entities_labels')
    op.drop_index('idx_artifacts_labels_name_value', table_name='artifacts_labels')
    # ### end Alembic commands ###
