"""Index ArtifactsV2 fields

Revision ID: fbad4d0029fd
Revises: 0b224a1b4e0d
Create Date: 2024-06-10 11:08:47.323372

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "fbad4d0029fd"
down_revision = "0b224a1b4e0d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_artifacts_v2_iteration"), "artifacts_v2", ["iteration"], unique=False
    )
    op.create_index(
        op.f("ix_artifacts_v2_producer_id"),
        "artifacts_v2",
        ["producer_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_artifacts_v2_project"), "artifacts_v2", ["project"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_artifacts_v2_project"), table_name="artifacts_v2")
    op.drop_index(op.f("ix_artifacts_v2_producer_id"), table_name="artifacts_v2")
    op.drop_index(op.f("ix_artifacts_v2_iteration"), table_name="artifacts_v2")
    # ### end Alembic commands ###
