name: Build Snapshot

on:
  push:
    branches:
      - development
      - feature/mlrun-release-procedure
  pull_request:
    branches:
      - development
      - release/*
  workflow_dispatch:
    inputs:
      skip_images:
        description: 'Comma separated list of images to skip building, example with all possible images: mlrun,api,models,jupyter,test'
        default: ''
        type: string
      build_from_cache:
        description: 'Whether to build images from cache or not. Default: true'
        default: 'true'
        type: string

permissions:
    id-token: write
    contents: read
    packages: write

jobs:
  prepare-context:
    outputs:
      mlrun_version: ${{ steps.get-version.outputs.mlrun_version }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v5

    - name: Get Version
    
      uses: ./.github/actions/get-version
      id: get-version

  build-mlrun:
    name: Build MLRun
    needs: prepare-context
    uses: ./.github/workflows/build.yaml
    with:
        tag: v$current_version-${{ github.run_id }}-${{ needs.prepare-context.outputs.mlrun_version }} 
    secrets: inherit