# Copyright 2025 Iguazio
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# 

name: Create Release Candidate
run-name: Create Release Candidate 

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'The type of release to create (major, minor, patch, or none)'
        required: false
        default: 'patch'
      source_branch:
        description: 'The source branch to create the release candidate from'
        required: false
        default: 'development'
jobs:
  build-mlrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpversion==0.6.0

      - name: Create Release Candidate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout {{ inputs.source_branch }}
          bumpversion {{inputs.release_type}}
          current_version=$(bumpversion --dry-run --list patch | grep current_version | sed 's/current_version=//')
          echo "New current version: $current_version"
          git checkout -b release/${{ github.run_id }}
          git push origin release-candidate-${{ github.run_id }}
          # TODO add changelog generation here as needed
          # gh release create "rc-v$current_version" --repo mlrun/mlrun --title "Release Candidate $current_version" --notes "Automated release candidate created by GitHub Actions" --prerelease
